### ISSUE TITLE
How to download the ver 1.1

### ISSUE THREAD

**Issue by SiTWulf** [ManlyMarco/Illusion_ClothingStateMenu#1]
I not like to use the MoreAccessories and the old version works like a charm... with this new version not work!

**Comment by ManlyMarco** [comment]
You most likely have outdated MoreAccessories, grab the newest version. Also get the v2.1 that I just released.

**Comment by SiTWulf** [comment]
Sorry @ManlyMarco but i NOT like to use MoreAccesories... i only want the old version of ClothingState for no use the new MoreAccesories.

**Comment by ManlyMarco** [comment]
In this case you will have to use the old version of ClothingStateMenu. All versions going forward will need the newest MoreAccesories. I was not the one who released it, so you will have to find it somewhere else.
