### ISSUE TITLE
Issue with Clothing State Menu

### ISSUE THREAD

**Issue by ghost** [ManlyMarco/Illusion_ClothingStateMenu#5]
Okay so I think there is an issue with Clothing State Menu (**Koikatsu!**) properly displaying all of the character accessories in Free H if you use more than default amount the game allows. Some of my characters exceed the default amount and thats when I notice that accessories towards the the bottom of the Clothing State Menu (**Slot 26,27,28 etc, etc**) List don't display at all or just wont toggle between on and off, it just stays ON. All of my character accessories show up fine in the character maker, its only in Free H where the issue comes up for me. The only workaround I've found is to load and re save that character in the maker and then go into Free H but even that doesn't work all of the time.

As of writing this I am using the **BR6 / Hotfix1** version of **Koikatsu!** - Picture 1 shows the total amount of accessories this character uses, picture 2 shows that I turned off accessory 26 but Clothing State Menu still shows that it is on. Lastly picture 3 shows the same character but now Clothing State Menu says that I only have 20 accessories total.

![1](https://user-images.githubusercontent.com/70109869/90987696-89312600-e552-11ea-8901-b190a0e27ea9.png)

![2](https://user-images.githubusercontent.com/70109869/90987709-99e19c00-e552-11ea-836f-25ea214d4a75.png)

![3](https://user-images.githubusercontent.com/70109869/90987711-9fd77d00-e552-11ea-8196-f1126021c837.png)

**Comment by ManlyMarco** [comment]
It's already fixed in 3ae5c8ea805e04dc3cef912308fefce094817c2c just not released yet. You can compile from source code to get the fix, or wait until I release an update (I'm waiting for more changes for now).
