### ISSUE TITLE
Koikatsu! - Clothing State Menu accessory buttons not working.

### ISSUE THREAD

**Issue by ghost** [ManlyMarco/Illusion_ClothingStateMenu#6]
When I updated to the latest HF patch (3.11) CSM no longer turns off/on all accessories from the buttons, you can still turn off accessories individually though. I went and ahead and deleted the version included with HF and DL'ed the latest release along with the most recent BepInEx and KKAPI and it still wouldn't work.

**Comment by ManlyMarco** [comment]
It's caused by KK_AccStateSync, you can remove it or try a different version if you need it.

**Comment by ghost** [comment]
Understood
