### ISSUE TITLE
Outfit options disappear when changing outfits for Male in Free H.

### ISSUE THREAD

**Issue by Saellys** [ManlyMarco/Illusion_ClothingStateMenu#7]
![image](https://user-images.githubusercontent.com/22218939/187866807-737b5c68-a152-4c0f-93b2-2bde3ea7647a.png)
![image](https://user-images.githubusercontent.com/22218939/187866829-ab1ab768-7c25-4295-9c55-1805993f6177.png)
With both MoreAccessories and ClothingStateMenu updated, I've noticed an issue with swapping the "Male" character's outfit. Some outfits will load, some will not, possibly related to accessory count but I can't be certain. 
Check Line 1240 in the output log for the start of the repeating error that occurs in this instance. This error seems to repeat infinitely as long as I keep the program open. Functionality is restored by leaving Free H and starting it again, but breaks again through the same process.

**Comment by ManlyMarco** [comment]
I can't reproduce the issue, switching outfits works fine even above 20 accessories. Make sure you're using latest versions of both plugins. Ideally I'd like detailed steps on how to reproduce the issue. Looks like you didn't send the log file anywhere, can you send it?

**Comment by Saellys** [comment]
Wow this was a while ago. Sorry to say the issue is gone now, updated plugins a few times since then and never seen it again. Haven't been using free H that much anyway to be fair. I'll give it a check when I get home later and let you know if it does or doesn't work. From recent memory I haven't had the issue anymore though.
